const guides=[
 {id:1,name:'Ravi Menon',type:'Birding',location:'Thattekad, Kerala',tag:'TOP MATCH',rating:'4.9',reviews:38,experience:'15 yrs',price:'₹5,500',image:'https://images.unsplash.com/photo-1542909168-82c3e7fdca5c?auto=format&fit=crop&w=800&q=85',chips:['Bird calls','Forest ecology'],bio:'A patient field naturalist who reads the Western Ghats by sound. Ravi is known for unhurried walks, rare endemics and thoughtful trips for first-time birders.'},
 {id:2,name:'Meera Joshi',type:'Wildlife',location:'Bera, Rajasthan',tag:'VERIFIED',rating:'4.9',reviews:27,experience:'12 yrs',price:'₹7,000',image:'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?auto=format&fit=crop&w=800&q=85',chips:['Leopards','Photography'],bio:'Naturalist and leopard tracker with deep relationships across the rocky Aravalli landscape. Meera shapes quiet, ethical encounters for photographers and families.'},
 {id:3,name:'Tashi Norbu',type:'Hiking',location:'Eaglenest, Arunachal',tag:'LOCAL EXPERT',rating:'4.8',reviews:19,experience:'10 yrs',price:'₹6,200',image:'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=800&q=85',chips:['High altitude','Birding'],bio:'Born in the eastern Himalaya, Tashi combines mountain craft with a remarkable eye for birds. His trips balance early starts, warm camp meals and local stories.'},
 {id:4,name:'Ananya Rao',type:'Herping',location:'Agumbe, Karnataka',tag:'NIGHT TRAILS',rating:'4.9',reviews:22,experience:'8 yrs',price:'₹4,800',image:'https://images.unsplash.com/photo-1531123897727-8f129e1688ce?auto=format&fit=crop&w=800&q=85',chips:['Reptiles','Amphibians'],bio:'A conservation educator fascinated by the small, secretive lives of the rainforest. Ananya leads safe night walks with a strong leave-no-trace ethic.'},
 {id:5,name:'Kabir Singh',type:'Wildlife',location:'Satpura, Madhya Pradesh',tag:'FAMILY FRIENDLY',rating:'4.7',reviews:31,experience:'9 yrs',price:'₹6,800',image:'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=800&q=85',chips:['Mammals','Canoe safari'],bio:'Kabir makes central India’s forests vivid for curious travelers of every age, connecting animal signs, trees and local history into one memorable story.'},
 {id:6,name:'Lhamo Dolma',type:'Hiking',location:'Sikkim',tag:'NEW ON FMG',rating:'5.0',reviews:12,experience:'7 yrs',price:'₹5,900',image:'https://images.unsplash.com/photo-1534751516642-a1af1ef26a56?auto=format&fit=crop&w=800&q=85',chips:['Alpine flora','Slow travel'],bio:'Lhamo leads intimate trails through Sikkim’s rhododendron country, with a love for alpine botany, village kitchens and trips that leave room to pause.'}
];

const grid=document.querySelector('#guideGrid');
function renderGuides(filter='all',query=''){
 const q=query.trim().toLowerCase(); const visible=guides.filter(g=>{const searchable=[g.name,g.type,g.location,g.tag,g.experience,...g.chips].join(' ').toLowerCase();return(filter==='all'||g.type===filter)&&(!q||searchable.includes(q))});
 grid.innerHTML=visible.length?visible.map(g=>`<article class="guide-card" data-id="${g.id}"><div class="guide-img" style="background-image:url('${g.image}')"><span class="tag">${g.tag}</span><button class="heart" aria-label="Save ${g.name}">♡</button></div><div class="guide-info"><h3>${g.name}</h3><p>${g.location} · ${g.experience}</p><div class="chips"><span>${g.type}</span>${g.chips.map(c=>`<span>${c}</span>`).join('')}</div><div class="guide-footer"><span><strong>${g.rating} ★</strong> (${g.reviews})</span><span>from <strong>${g.price}</strong>/day</span></div></div></article>`).join(''):`<div class="empty-state"><h3>No exact matches yet.</h3><p>Try another place or browse all guides.</p></div>`;
}
renderGuides();
document.querySelector('#filters').addEventListener('click',e=>{if(!e.target.matches('.filter'))return;document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));e.target.classList.add('active');renderGuides(e.target.dataset.filter,document.querySelector('#locationInput').value)});
document.querySelector('#heroSearch').addEventListener('submit',e=>{e.preventDefault();const interest=document.querySelector('#interestInput').value;document.querySelectorAll('.filter').forEach(x=>x.classList.toggle('active',x.dataset.filter===interest));renderGuides(interest,document.querySelector('#locationInput').value);document.querySelector('#explore').scrollIntoView()});
document.querySelector('#locationInput').addEventListener('input',e=>{const active=document.querySelector('.filter.active')?.dataset.filter||'all';if(e.target.value.length===0||e.target.value.length>=2)renderGuides(active,e.target.value)});
grid.addEventListener('click',e=>{const heart=e.target.closest('.heart');if(heart){heart.textContent=heart.textContent==='♡'?'♥':'♡';heart.style.color=heart.textContent==='♥'?'#df6e55':'';showToast(heart.textContent==='♥'?'Saved to your shortlist':'Removed from shortlist');return}const card=e.target.closest('.guide-card');if(!card)return;openGuide(+card.dataset.id)});
function openGuide(id){const g=guides.find(x=>x.id===id);document.querySelector('#dialogContent').innerHTML=`<div class="dialog-profile"><div class="dialog-image" style="background-image:url('${g.image}')"></div><div class="dialog-copy"><span class="kicker">${g.tag}</span><h2>${g.name}</h2><p class="location">${g.type} guide · ${g.location}</p><div class="dialog-stats"><span><b>${g.rating} ★</b>${g.reviews} verified reviews</span><span><b>${g.experience}</b>experience</span><span><b>${g.price}</b>per day</span></div><p class="bio">${g.bio}</p><div class="chips">${g.chips.map(c=>`<span>${c}</span>`).join('')}</div><div class="mini-review"><span>★★★★★</span><p>“Patient, deeply knowledgeable and brilliantly organised.”</p><small>✓ Verified platform booking</small></div><div class="dialog-actions"><button class="button button-dark enquire" data-guide-id="${g.id}">Book this guide ↗</button><button class="button save-guide">♡ Save</button></div></div></div>`;document.querySelector('#guideDialog').showModal()}
document.querySelectorAll('.dialog').forEach(d=>{d.querySelector('.close').onclick=()=>d.close();d.addEventListener('click',e=>{if(e.target===d)d.close()})});
document.querySelector('#guideDialog').addEventListener('click',async e=>{if(e.target.matches('.enquire')){const id=+e.target.dataset.guideId;sessionStorage.setItem('fmgBookingDraft',String(id));e.currentTarget.close();try{const response=await fetch('/api/auth/session',{credentials:'same-origin'}),data=await response.json();if(data.user?.role==='traveler')openBooking(id);else location.href='traveler-login.html?next=book'}catch{location.href='traveler-login.html?next=book'}}if(e.target.matches('.save-guide')){e.target.textContent='♥ Saved';e.target.style.color='#df6e55'}});
document.querySelectorAll('[data-open="join"]').forEach(b=>b.onclick=()=>document.querySelector('#joinDialog').showModal());
document.querySelector('#dashboardBtn').onclick=()=>window.location.href='guide-login.html';
const joinForm=document.querySelector('#joinForm'); let currentStep=1;
function showFormStep(step){currentStep=step;document.querySelectorAll('.form-step').forEach(s=>s.classList.toggle('active',+s.dataset.step===step));document.querySelectorAll('.form-progress span').forEach((s,i)=>s.classList.toggle('active',i<step));document.querySelector('#joinDialog').scrollTop=0}
function validateStep(step){const section=document.querySelector(`.form-step[data-step="${step}"]`);if(step===2&&!section.querySelector('input[name="expertise"]:checked')){showToast('Select at least one area of expertise');return false}const required=[...section.querySelectorAll('[required]')];for(const field of required){if(!field.checkValidity()){field.reportValidity();return false}}return true}
document.querySelectorAll('.next-step').forEach(b=>b.onclick=()=>{if(validateStep(currentStep))showFormStep(currentStep+1)});
document.querySelectorAll('.back-step').forEach(b=>b.onclick=()=>showFormStep(currentStep-1));
document.querySelectorAll('.upload-box input').forEach(input=>input.addEventListener('change',()=>{const files=[...input.files];const invalid=files.find(f=>f.size>5*1024*1024);if(invalid){input.value='';showToast(`${invalid.name} is larger than 5 MB`);return}const preview=input.nextElementSibling;preview.classList.toggle('has-file',files.length>0);preview.innerHTML=files.length?`✓ ${files.length} photo${files.length>1?'s':''} selected<small>${files.map(f=>f.name).join(', ')}</small>`:`＋<small>Choose photos</small>`;document.querySelector('#fileSummary').textContent='Photos are previewed locally and submitted only with your application.'}));
joinForm.onsubmit=async e=>{
 e.preventDefault();if(!validateStep(4))return;
 const expertise=[...joinForm.querySelectorAll('input[name="expertise"]:checked')].map(x=>x.value),form=new FormData(joinForm),workLocations=String(form.get('workLocations')||'').split(/\n|,/).map(x=>x.trim()).filter(Boolean),languages=String(form.get('languages')||'').split(',').map(x=>x.trim()).filter(Boolean);
 const payload={name:form.get('name'),email:form.get('email'),phone:form.get('phone'),whatsapp:form.get('whatsapp'),primaryLocation:form.get('location'),states:String(form.get('states')||'').split(',').map(x=>x.trim()).filter(Boolean),workLocations,expertise,languages,yearsExperience:+form.get('experience'),dailyRate:+form.get('price')||0,bio:form.get('bio'),profilePhoto:form.get('profilePhoto')?.name||'',workPhotos:[...joinForm.querySelector('[name="workPhotos"]').files].map(f=>f.name),invitationToken:sessionStorage.getItem('fmgGuideInviteToken')||undefined};
 try{const response=await fetch('/api/guide-applications',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}),data=await response.json();if(!response.ok)throw new Error(data.error||'Application could not be submitted');sessionStorage.removeItem('fmgGuideInviteToken');sessionStorage.removeItem('fmgGuideInviteData');document.querySelector('#joinDialog').close();e.target.reset();showFormStep(1);showToast(`Application APP-${data.id} received — we’ll review it shortly.`)}catch(error){showToast(error.message)}
};
document.querySelector('#addTour').onclick=()=>showToast('New tour draft created');
let bookingGuide=null,bookingStart=null,bookingEnd=null,bookingAvailable=new Set();
function guideUnavailable(){return Array.from({length:31},(_,i)=>i+1).filter(day=>!bookingAvailable.has(day))}
function formatMoney(n){return new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(n)}
async function openBooking(id){bookingGuide=guides.find(g=>g.id===id);if(!bookingGuide)return;bookingStart=bookingEnd=null;document.querySelector('#bookingGuideName').textContent=bookingGuide.name;document.querySelector('#bookingGuideLabel').textContent=bookingGuide.name;document.querySelector('#bookingGuideMeta').textContent=`${bookingGuide.type} · ${bookingGuide.location}`;document.querySelector('#bookingGuideRating').textContent=`${bookingGuide.rating} ★`;document.querySelector('#bookingGuideAvatar').style.backgroundImage=`url('${bookingGuide.image}')`;document.querySelector('#guideBookingForm').reset();try{const response=await fetch(`/api/guides/${id}/availability?from=2026-10-01&to=2026-10-31`),data=await response.json();bookingAvailable=new Set((data.dates||[]).filter(x=>x.status==='available').map(x=>Number(x.date.slice(-2))))}catch{bookingAvailable=new Set()}renderPublicCalendar();updateBookingPrice();document.querySelector('#bookingDialog').showModal()}
function renderPublicCalendar(){const cal=document.querySelector('#publicBookingCalendar'),names=['MON','TUE','WED','THU','FRI','SAT','SUN'],unavailable=guideUnavailable();let html=names.map(x=>`<span class="public-cal-head">${x}</span>`).join('');for(let i=0;i<3;i++)html+='<span></span>';for(let day=1;day<=31;day++){const off=unavailable.includes(day),selected=bookingStart&&day>=bookingStart&&day<=(bookingEnd||bookingStart);html+=`<button type="button" data-book-day="${day}" class="${off?'unavailable':''} ${selected?'selected':''}" ${off?'disabled':''} aria-label="October ${day}, ${off?'unavailable':'available'}">${day}</button>`}cal.innerHTML=html;document.querySelector('#dateSelection').textContent=!bookingStart?'No dates selected':bookingEnd?`${bookingStart}–${bookingEnd} October 2026 · ${bookingEnd-bookingStart+1} days`:`Start: ${bookingStart} October · now choose an end date`}
document.querySelector('#publicBookingCalendar').onclick=e=>{const b=e.target.closest('[data-book-day]');if(!b)return;const day=+b.dataset.bookDay,blocked=guideUnavailable();if(!bookingStart||bookingEnd){bookingStart=day;bookingEnd=null}else if(day<bookingStart){bookingStart=day}else{const conflict=blocked.some(d=>d>=bookingStart&&d<=day);if(conflict){showToast('That range contains an unavailable date. Choose a shorter range.');return}bookingEnd=day}renderPublicCalendar();updateBookingPrice()};
function updateBookingPrice(){const daily=bookingGuide?Number(bookingGuide.price.replace(/[^0-9]/g,'')):0,days=bookingStart?(bookingEnd||bookingStart)-bookingStart+1:0,subtotal=daily*days,fee=0,total=subtotal;document.querySelector('#priceDays').textContent=days;document.querySelector('#priceDaily').textContent=formatMoney(daily);document.querySelector('#priceSubtotal').textContent=formatMoney(subtotal);document.querySelector('#priceFee').textContent=formatMoney(fee);document.querySelector('#priceTotal').textContent=formatMoney(total);return{daily,days,subtotal,fee,total}}
document.querySelector('#guideBookingForm').onsubmit=async e=>{e.preventDefault();if(!bookingStart||!bookingEnd){showToast('Select both a start date and an end date');return}if(!e.currentTarget.checkValidity()){e.currentTarget.reportValidity();return}try{const inviteToken=sessionStorage.getItem('fmgInviteToken'),response=await fetch('/api/booking-requests',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify({guideId:bookingGuide.id,startDate:`2026-10-${String(bookingStart).padStart(2,'0')}`,endDate:`2026-10-${String(bookingEnd).padStart(2,'0')}`,travelers:+document.querySelector('#bookingTravelers').value,focus:document.querySelector('#bookingFocus').value,message:document.querySelector('#bookingMessage').value,invitationToken:inviteToken||undefined})}),data=await response.json();if(!response.ok)throw new Error(data.error||'Could not send booking request');sessionStorage.setItem('fmgLastRequest',JSON.stringify({...data.request,guide:bookingGuide.name,guideImage:bookingGuide.image,location:bookingGuide.location}));sessionStorage.removeItem('fmgBookingDraft');sessionStorage.removeItem('fmgInviteToken');location.href='traveler-panel.html#requests'}catch(error){showToast(error.message)}};
const bookingQuery=+new URLSearchParams(location.search).get('book');if(bookingQuery)setTimeout(async()=>{try{const data=await (await fetch('/api/auth/session',{credentials:'same-origin'})).json();if(data.user?.role==='traveler')openBooking(bookingQuery);else location.href='traveler-login.html?next=book'}catch{location.href='traveler-login.html?next=book'}},0);
document.querySelector('#guideBookingForm button[type="submit"]').textContent='Send booking request ↗';document.querySelector('.payment-note').textContent='The guide will accept or decline within 24 hours. Pay the guide directly after confirmation.';document.querySelector('.price-breakdown h3').textContent='Estimated guide fee';document.querySelector('.price-total i').textContent='Estimated total';document.querySelector('.booking-consent span').textContent='I understand this is a request, not a confirmed booking, and payment will be arranged directly with the guide.';
const joinQuery=new URLSearchParams(location.search).get('join');if(joinQuery==='guide')setTimeout(()=>{const saved=JSON.parse(sessionStorage.getItem('fmgGuideInviteData')||'{}');for(const [name,value] of Object.entries({name:saved.name,email:saved.email,phone:saved.phone,whatsapp:saved.phone})){const input=joinForm.elements[name];if(input&&value)input.value=value}document.querySelector('#joinDialog').showModal()},0);
const calendarState={3:'blocked',7:'booked',8:'booked',9:'booked',18:'booked',19:'booked',20:'booked',21:'booked',22:'booked',27:'booked',28:'booked'};
function renderCalendar(){const cal=document.querySelector('#availabilityCalendar');const days=['MON','TUE','WED','THU','FRI','SAT','SUN'];let html=days.map(d=>`<span class="cal-day header">${d}</span>`).join('');for(let i=0;i<3;i++)html+='<span class="cal-day empty"></span>';for(let d=1;d<=31;d++){const status=calendarState[d]||'available';html+=`<button class="cal-day ${status}" data-day="${d}" data-status="${status}" aria-label="October ${d}, ${status}">${d}</button>`}cal.innerHTML=html;updateCalendarCounts()}
function updateCalendarCounts(){const states=Object.values(calendarState);const booked=states.filter(x=>x==='booked').length,blocked=states.filter(x=>x==='blocked').length;document.querySelector('#bookedCount').textContent=booked;document.querySelector('#blockedCount').textContent=blocked;document.querySelector('#availableCount').textContent=31-booked-blocked}
renderCalendar();
document.querySelector('#availabilityCalendar').onclick=e=>{const day=e.target.closest('[data-day]');if(!day)return;const cycle={available:'booked',booked:'blocked',blocked:'available'};const next=cycle[day.dataset.status];if(next==='available')delete calendarState[day.dataset.day];else calendarState[day.dataset.day]=next;renderCalendar()};
document.querySelector('#saveCalendar').onclick=()=>showToast('Availability saved and visible to travelers');
document.querySelector('.workspace-tabs').onclick=e=>{const button=e.target.closest('[data-admin-tab]');if(!button)return;document.querySelectorAll('.workspace-tabs button').forEach(b=>b.classList.toggle('active',b===button));document.querySelectorAll('.admin-panel').forEach(p=>p.classList.toggle('active',p.dataset.panel===button.dataset.adminTab))};
document.querySelectorAll('[data-scroll]').forEach(b=>b.onclick=()=>document.querySelector('#'+b.dataset.scroll).scrollIntoView());
document.querySelector('#viewAll').onclick=e=>{e.preventDefault();document.querySelectorAll('.filter').forEach(x=>x.classList.toggle('active',x.dataset.filter==='all'));renderGuides()};
document.querySelector('#menuBtn').onclick=()=>{document.querySelector('#explore').scrollIntoView()};
function showToast(message){const t=document.querySelector('#toast');t.textContent=message;t.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>t.classList.remove('show'),3000)}
