import { body, bookingDto, cleanText, createSession, db, fail, guideDto, hashPassword, json, parseCookies, publicUser, randomBytes, reply, requireUser, sessionUser, sha256, verifyPassword, SESSION_COOKIE } from './context.mjs';

const routes = [];
const route = (method, pattern, handler) => routes.push({ method, pattern, handler });

route('GET', /^\/api\/health$/, (_req,res) => reply(res,200,{ status:'ok',service:'findmyguide-api',database:'sqlite' }));
route('GET', /^\/api\/auth\/session$/, (req,res) => reply(res,200,{ user:publicUser(sessionUser(req)) }));
route('POST', /^\/api\/auth\/register$/, async (req,res) => {
  const data = await body(req), name=cleanText(data.name,100), email=cleanText(data.email,180).toLowerCase(), phone=cleanText(data.phone,30), location=cleanText(data.location,150), password=String(data.password||''), interests=Array.isArray(data.interests)?data.interests.map(x=>cleanText(x,60)).filter(Boolean).slice(0,12):[];
  if (!name || !/^\S+@\S+\.\S+$/.test(email) || !phone || !location || password.length < 8 || !interests.length) return fail(res,400,'Name, valid email, phone, location, interests and an 8-character password are required');
  if (db.prepare('SELECT id FROM users WHERE email=?').get(email)) return fail(res,409,'An account with this email already exists');
  db.exec('BEGIN');
  try { const result=db.prepare('INSERT INTO users(role,name,email,phone,password_hash) VALUES(?,?,?,?,?)').run('traveler',name,email,phone,hashPassword(password)); const id=Number(result.lastInsertRowid); db.prepare('INSERT INTO traveler_profiles(user_id,home_location,interests_json) VALUES(?,?,?)').run(id,location,JSON.stringify(interests)); db.exec('COMMIT'); createSession(res,id); reply(res,201,{ user:{id,role:'traveler',name,email,phone},profile:{location,interests} }); } catch(e){ db.exec('ROLLBACK'); throw e; }
});
route('POST', /^\/api\/auth\/login$/, async (req,res) => {
  const data=await body(req), identity=cleanText(data.identity||data.email,180).toLowerCase(), user=db.prepare('SELECT * FROM users WHERE (lower(email)=? OR phone=?) AND status=?').get(identity,identity,'active');
  if (!user || !verifyPassword(String(data.password||''),user.password_hash)) return fail(res,401,'Invalid email, phone or password');
  if (data.role && user.role !== data.role) return fail(res,403,`This account is not registered as ${data.role}`);
  createSession(res,user.id); reply(res,200,{ user:publicUser(user) });
});
route('POST', /^\/api\/auth\/logout$/, (req,res) => { const token=parseCookies(req)[SESSION_COOKIE]; if(token) db.prepare('DELETE FROM sessions WHERE token_hash=?').run(sha256(token)); res.setHeader('Set-Cookie',`${SESSION_COOKIE}=; HttpOnly; SameSite=Strict; Path=/; Max-Age=0`); reply(res,200,{ok:true}); });

route('GET', /^\/api\/guides$/, (req,res,url) => {
  const q=cleanText(url.searchParams.get('q'),100).toLowerCase(), expertise=cleanText(url.searchParams.get('expertise'),60).toLowerCase();
  const rows=db.prepare("SELECT * FROM guide_profiles WHERE verification_status='approved' ORDER BY rating DESC,review_count DESC").all().map(guideDto).filter(g=>{const hay=[g.name,g.location,...g.workLocations,...g.expertise].join(' ').toLowerCase();return(!q||hay.includes(q))&&(!expertise||g.expertise.some(x=>x.toLowerCase().includes(expertise)));});
  reply(res,200,{guides:rows});
});
route('GET', /^\/api\/guides\/(\d+)$/, (req,res,_url,match) => { const row=db.prepare("SELECT * FROM guide_profiles WHERE id=? AND verification_status='approved'").get(Number(match[1])); if(!row)return fail(res,404,'Guide not found'); const reviews=db.prepare("SELECT r.*,u.name traveler_name FROM reviews r JOIN users u ON u.id=r.traveler_id WHERE r.guide_id=? AND r.status='published' ORDER BY r.created_at DESC LIMIT 20").all(row.id); reply(res,200,{guide:guideDto(row),reviews}); });
route('GET', /^\/api\/guides\/(\d+)\/availability$/, (req,res,url,match) => { const guideId=Number(match[1]),from=url.searchParams.get('from')||'2026-10-01',to=url.searchParams.get('to')||'2026-10-31'; const dates=db.prepare("SELECT date,status FROM availability WHERE guide_id=? AND status='available' AND date BETWEEN ? AND ? ORDER BY date").all(guideId,from,to); reply(res,200,{guideId,from,to,dates}); });

route('POST', /^\/api\/guide-applications$/, async (req,res) => {
  const data=await body(req), expertise=Array.isArray(data.expertise)?data.expertise.slice(0,12):[], work=Array.isArray(data.workLocations)?data.workLocations.slice(0,30):[], languages=Array.isArray(data.languages)?data.languages.slice(0,15):[];
  const required=['name','email','phone','primaryLocation','bio']; if(required.some(k=>!cleanText(data[k])))return fail(res,400,'Missing required application fields'); if(!expertise.length||!work.length||Number(data.yearsExperience)<0)return fail(res,400,'Expertise, work locations and valid experience are required');
  const user=sessionUser(req); const result=db.prepare(`INSERT INTO guide_applications(applicant_user_id,name,email,phone,whatsapp,primary_location,states_json,work_locations_json,expertise_json,languages_json,years_experience,daily_rate,bio,profile_photo,work_photos_json) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).run(user?.id||null,cleanText(data.name,100),cleanText(data.email,180).toLowerCase(),cleanText(data.phone,30),cleanText(data.whatsapp,30),cleanText(data.primaryLocation,150),JSON.stringify(data.states||[]),JSON.stringify(work),JSON.stringify(expertise),JSON.stringify(languages),Number(data.yearsExperience),Number(data.dailyRate||0),cleanText(data.bio,1500),cleanText(data.profilePhoto,500),JSON.stringify(data.workPhotos||[]));
  if(data.invitationToken){const invite=db.prepare("SELECT id FROM invitations WHERE token_hash=? AND kind='guide_onboarding' AND status IN ('sent','opened') AND expires_at>datetime('now')").get(sha256(String(data.invitationToken)));if(invite)db.prepare("UPDATE invitations SET status='accepted',accepted_at=datetime('now') WHERE id=?").run(invite.id);}
  reply(res,201,{id:Number(result.lastInsertRowid),status:'pending'});
});

route('GET', /^\/api\/admin\/applications$/, (req,res,url) => { if(!requireUser(req,res,['admin']))return; const status=url.searchParams.get('status')||'pending'; const rows=db.prepare('SELECT * FROM guide_applications WHERE status=? ORDER BY created_at ASC').all(status).map(r=>({...r,states:json(r.states_json),workLocations:json(r.work_locations_json),expertise:json(r.expertise_json),languages:json(r.languages_json),workPhotos:json(r.work_photos_json)})); reply(res,200,{applications:rows}); });
route('PATCH', /^\/api\/admin\/applications\/(\d+)$/, async (req,res,_url,match) => {
  const admin=requireUser(req,res,['admin']); if(!admin)return; const id=Number(match[1]),data=await body(req),decision=data.decision; if(!['approved','rejected','needs_information'].includes(decision))return fail(res,400,'Invalid decision'); const app=db.prepare('SELECT * FROM guide_applications WHERE id=?').get(id); if(!app)return fail(res,404,'Application not found');
  db.exec('BEGIN'); try { db.prepare("UPDATE guide_applications SET status=?,admin_note=?,reviewed_by=?,reviewed_at=datetime('now') WHERE id=?").run(decision,cleanText(data.note,1000),admin.id,id); if(decision==='approved'){let user=db.prepare('SELECT * FROM users WHERE email=?').get(app.email);let userId=user?.id;if(!userId){userId=Number(db.prepare('INSERT INTO users(role,name,email,phone,password_hash,status) VALUES(?,?,?,?,?,?)').run('guide',app.name,app.email,app.phone,hashPassword(randomBytes(12).toString('base64url')),'active').lastInsertRowid);}else db.prepare("UPDATE users SET role='guide' WHERE id=?").run(userId);db.prepare(`INSERT INTO guide_profiles(user_id,display_name,primary_location,work_locations_json,expertise_json,languages_json,years_experience,bio,daily_rate,profile_photo,work_photos_json) VALUES(?,?,?,?,?,?,?,?,?,?,?)`).run(userId,app.name,app.primary_location,app.work_locations_json,app.expertise_json,app.languages_json,app.years_experience,app.bio,app.daily_rate,app.profile_photo,app.work_photos_json);} db.exec('COMMIT'); reply(res,200,{id,status:decision}); }catch(e){db.exec('ROLLBACK');throw e;}
});
route('GET', /^\/api\/admin\/dashboard$/, (req,res) => { if(!requireUser(req,res,['admin']))return; const counts={guides:db.prepare("SELECT count(*) count FROM guide_profiles WHERE verification_status='approved'").get().count,pendingApplications:db.prepare("SELECT count(*) count FROM guide_applications WHERE status='pending'").get().count,travelers:db.prepare("SELECT count(*) count FROM users WHERE role='traveler'").get().count,pendingRequests:db.prepare("SELECT count(*) count FROM booking_requests WHERE status='pending' AND response_deadline>datetime('now')").get().count,confirmedBookings:db.prepare("SELECT count(*) count FROM bookings WHERE status IN ('confirmed','completed')").get().count,recordedBookingValue:db.prepare("SELECT coalesce(sum(total),0) total FROM bookings WHERE status IN ('confirmed','completed')").get().total,guideInvitations:db.prepare("SELECT count(*) count FROM invitations WHERE kind='guide_onboarding'").get().count,clientInvitations:db.prepare("SELECT count(*) count FROM invitations WHERE kind='client_booking'").get().count}; reply(res,200,{counts}); });
function adminPage(url){const page=Math.max(1,Number(url.searchParams.get('page'))||1),limit=Math.min(500,Math.max(1,Number(url.searchParams.get('limit'))||100));return{page,limit,offset:(page-1)*limit};}
route('GET', /^\/api\/admin\/guides$/, (req,res,url) => { if(!requireUser(req,res,['admin']))return;const {page,limit,offset}=adminPage(url),q=cleanText(url.searchParams.get('q'),100).toLowerCase(),status=cleanText(url.searchParams.get('status'),30),location=cleanText(url.searchParams.get('location'),100).toLowerCase(),expertise=cleanText(url.searchParams.get('expertise'),60).toLowerCase(),where=[],params=[];if(q){where.push('(lower(g.display_name) LIKE ? OR lower(g.primary_location) LIKE ? OR lower(g.expertise_json) LIKE ? OR lower(coalesce(u.email,\'\')) LIKE ? OR lower(coalesce(u.phone,\'\')) LIKE ?)');params.push(...Array(5).fill(`%${q}%`));}if(status){where.push('g.verification_status=?');params.push(status);}if(location){where.push('lower(g.primary_location) LIKE ?');params.push(`%${location}%`);}if(expertise){where.push('lower(g.expertise_json) LIKE ?');params.push(`%${expertise}%`);}const clause=where.length?`WHERE ${where.join(' AND ')}`:'',total=db.prepare(`SELECT count(*) count FROM guide_profiles g LEFT JOIN users u ON u.id=g.user_id ${clause}`).get(...params).count,rows=db.prepare(`SELECT g.*,u.name account_name,u.email,u.phone,u.status account_status,(SELECT count(*) FROM bookings b WHERE b.guide_id=g.id) booking_count,(SELECT count(*) FROM booking_requests r WHERE r.guide_id=g.id) request_count,(SELECT count(*) FROM booking_requests r WHERE r.guide_id=g.id AND r.status='pending') pending_request_count,(SELECT count(*) FROM availability a WHERE a.guide_id=g.id AND a.status='available') available_date_count,(SELECT count(*) FROM invitations i WHERE i.guide_id=g.id AND i.kind='client_booking') client_invite_count,(SELECT coalesce(sum(b.total),0) FROM bookings b WHERE b.guide_id=g.id AND b.status IN ('confirmed','completed')) recorded_value FROM guide_profiles g LEFT JOIN users u ON u.id=g.user_id ${clause} ORDER BY g.created_at DESC LIMIT ? OFFSET ?`).all(...params,limit,offset).map(r=>({...r,expertise:json(r.expertise_json),workLocations:json(r.work_locations_json),languages:json(r.languages_json)}));reply(res,200,{guides:rows,meta:{page,limit,total,pages:Math.ceil(total/limit)}}); });
route('GET', /^\/api\/admin\/users$/, (req,res,url) => { if(!requireUser(req,res,['admin']))return;const {page,limit,offset}=adminPage(url),q=cleanText(url.searchParams.get('q'),100).toLowerCase(),role=cleanText(url.searchParams.get('role'),20),status=cleanText(url.searchParams.get('status'),20),location=cleanText(url.searchParams.get('location'),100).toLowerCase(),booked=cleanText(url.searchParams.get('booked'),10),where=[],params=[];if(q){where.push('(lower(u.name) LIKE ? OR lower(u.email) LIKE ? OR lower(coalesce(u.phone,\'\')) LIKE ? OR lower(coalesce(t.home_location,g.primary_location,\'\')) LIKE ?)');params.push(...Array(4).fill(`%${q}%`));}if(role){where.push('u.role=?');params.push(role);}if(status){where.push('u.status=?');params.push(status);}if(location){where.push('lower(coalesce(t.home_location,g.primary_location,\'\')) LIKE ?');params.push(`%${location}%`);}if(booked==='yes')where.push('(SELECT count(*) FROM bookings b WHERE b.traveler_id=u.id OR b.guide_id=g.id)>0');if(booked==='no')where.push('(SELECT count(*) FROM bookings b WHERE b.traveler_id=u.id OR b.guide_id=g.id)=0');const clause=where.length?`WHERE ${where.join(' AND ')}`:'',base='FROM users u LEFT JOIN traveler_profiles t ON t.user_id=u.id LEFT JOIN guide_profiles g ON g.user_id=u.id',total=db.prepare(`SELECT count(*) count ${base} ${clause}`).get(...params).count,rows=db.prepare(`SELECT u.id,u.role,u.name,u.email,u.phone,u.status,u.created_at,u.updated_at,coalesce(t.home_location,g.primary_location,'') location,t.interests_json,g.id guide_id,g.display_name guide_name,g.verification_status,(SELECT count(*) FROM bookings b WHERE b.traveler_id=u.id) traveler_booking_count,(SELECT count(*) FROM booking_requests r WHERE r.traveler_id=u.id) traveler_request_count,(SELECT count(*) FROM bookings b WHERE b.guide_id=g.id) guide_booking_count,(SELECT coalesce(sum(b.total),0) FROM bookings b WHERE b.traveler_id=u.id AND b.status IN ('confirmed','completed')) booking_value,(SELECT max(b.created_at) FROM bookings b WHERE b.traveler_id=u.id OR b.guide_id=g.id) last_booking_at ${base} ${clause} ORDER BY u.created_at DESC LIMIT ? OFFSET ?`).all(...params,limit,offset).map(r=>({...r,interests:json(r.interests_json)}));reply(res,200,{users:rows,meta:{page,limit,total,pages:Math.ceil(total/limit)}}); });
route('GET', /^\/api\/admin\/booking-requests$/, (req,res,url) => { if(!requireUser(req,res,['admin']))return;db.prepare("UPDATE booking_requests SET status='expired' WHERE status='pending' AND response_deadline<=datetime('now')").run();const {page,limit,offset}=adminPage(url),q=cleanText(url.searchParams.get('q'),100).toLowerCase(),status=cleanText(url.searchParams.get('status'),20),source=cleanText(url.searchParams.get('source'),20),where=[],params=[];if(q){where.push('(lower(r.reference) LIKE ? OR lower(u.name) LIKE ? OR lower(g.display_name) LIKE ? OR lower(r.focus) LIKE ?)');params.push(...Array(4).fill(`%${q}%`));}if(status){where.push('r.status=?');params.push(status);}if(source==='invited')where.push('r.invitation_id IS NOT NULL');if(source==='direct')where.push('r.invitation_id IS NULL');const clause=where.length?`WHERE ${where.join(' AND ')}`:'',base='FROM booking_requests r JOIN users u ON u.id=r.traveler_id JOIN guide_profiles g ON g.id=r.guide_id LEFT JOIN invitations i ON i.id=r.invitation_id',total=db.prepare(`SELECT count(*) count ${base} ${clause}`).get(...params).count,rows=db.prepare(`SELECT r.*,u.name traveler_name,u.email traveler_email,u.phone traveler_phone,g.display_name guide_name,g.primary_location guide_location,i.recipient_name invited_client_name ${base} ${clause} ORDER BY CASE r.status WHEN 'pending' THEN 0 ELSE 1 END,r.created_at DESC LIMIT ? OFFSET ?`).all(...params,limit,offset);reply(res,200,{requests:rows,meta:{page,limit,total,pages:Math.ceil(total/limit)}}); });
route('GET', /^\/api\/admin\/bookings$/, (req,res,url) => { if(!requireUser(req,res,['admin']))return;const {page,limit,offset}=adminPage(url),q=cleanText(url.searchParams.get('q'),100).toLowerCase(),status=cleanText(url.searchParams.get('status'),20),payment=cleanText(url.searchParams.get('paymentStatus'),30),from=cleanText(url.searchParams.get('from'),10),to=cleanText(url.searchParams.get('to'),10),where=[],params=[];if(q){where.push('(lower(b.reference) LIKE ? OR lower(u.name) LIKE ? OR lower(g.display_name) LIKE ? OR lower(b.focus) LIKE ?)');params.push(...Array(4).fill(`%${q}%`));}if(status){where.push('b.status=?');params.push(status);}if(payment){where.push("coalesce(d.status,'not_recorded')=?");params.push(payment);}if(/^\d{4}-\d{2}-\d{2}$/.test(from)){where.push('b.start_date>=?');params.push(from);}if(/^\d{4}-\d{2}-\d{2}$/.test(to)){where.push('b.end_date<=?');params.push(to);}const clause=where.length?`WHERE ${where.join(' AND ')}`:'',base='FROM bookings b JOIN users u ON u.id=b.traveler_id JOIN guide_profiles g ON g.id=b.guide_id LEFT JOIN direct_payment_records d ON d.booking_id=b.id',total=db.prepare(`SELECT count(*) count ${base} ${clause}`).get(...params).count,rows=db.prepare(`SELECT b.*,u.name traveler_name,u.email traveler_email,u.phone traveler_phone,g.display_name guide_name,g.primary_location guide_location,coalesce(d.status,'not_recorded') payment_record_status,d.amount_recorded,d.note payment_note ${base} ${clause} ORDER BY b.created_at DESC LIMIT ? OFFSET ?`).all(...params,limit,offset);reply(res,200,{bookings:rows,meta:{page,limit,total,pages:Math.ceil(total/limit)}}); });
route('GET', /^\/api\/admin\/reviews$/, (req,res,url) => { if(!requireUser(req,res,['admin']))return;const {page,limit,offset}=adminPage(url),q=cleanText(url.searchParams.get('q'),100).toLowerCase(),status=cleanText(url.searchParams.get('status'),20),rating=Number(url.searchParams.get('rating'))||0,where=[],params=[];if(q){where.push('(lower(r.title) LIKE ? OR lower(r.body) LIKE ? OR lower(u.name) LIKE ? OR lower(g.display_name) LIKE ? OR lower(b.reference) LIKE ?)');params.push(...Array(5).fill(`%${q}%`));}if(status){where.push('r.status=?');params.push(status);}if(rating){where.push('r.overall=?');params.push(rating);}const clause=where.length?`WHERE ${where.join(' AND ')}`:'',base='FROM reviews r JOIN users u ON u.id=r.traveler_id JOIN guide_profiles g ON g.id=r.guide_id JOIN bookings b ON b.id=r.booking_id',total=db.prepare(`SELECT count(*) count ${base} ${clause}`).get(...params).count,rows=db.prepare(`SELECT r.*,u.name traveler_name,u.email traveler_email,g.display_name guide_name,b.reference booking_reference,b.start_date,b.end_date ${base} ${clause} ORDER BY r.created_at DESC LIMIT ? OFFSET ?`).all(...params,limit,offset).map(r=>({...r,photos:json(r.photos_json)}));reply(res,200,{reviews:rows,meta:{page,limit,total,pages:Math.ceil(total/limit)}}); });

route('GET', /^\/api\/traveler\/profile$/, (req,res) => { const user=requireUser(req,res,['traveler']);if(!user)return;const profile=db.prepare('SELECT * FROM traveler_profiles WHERE user_id=?').get(user.id);reply(res,200,{user:publicUser(user),profile:{location:profile?.home_location||'',interests:json(profile?.interests_json)}}); });
route('PATCH', /^\/api\/traveler\/profile$/, async (req,res) => { const user=requireUser(req,res,['traveler']);if(!user)return;const data=await body(req);db.prepare("UPDATE users SET name=?,phone=?,updated_at=datetime('now') WHERE id=?").run(cleanText(data.name,100)||user.name,cleanText(data.phone,30)||user.phone,user.id);db.prepare(`INSERT INTO traveler_profiles(user_id,home_location,interests_json) VALUES(?,?,?) ON CONFLICT(user_id) DO UPDATE SET home_location=excluded.home_location,interests_json=excluded.interests_json`).run(user.id,cleanText(data.location,150),JSON.stringify(Array.isArray(data.interests)?data.interests.slice(0,12):[]));reply(res,200,{ok:true}); });

function createInvitation({kind,inviterUserId,guideId=null,name='',email='',phone='',message='',hours=168}) {
  const token=randomBytes(24).toString('base64url'),result=db.prepare(`INSERT INTO invitations(kind,token_hash,inviter_user_id,guide_id,recipient_name,recipient_email,recipient_phone,message,expires_at) VALUES(?,?,?,?,?,?,?,?,datetime('now',?))`).run(kind,sha256(token),inviterUserId,guideId,cleanText(name,100),cleanText(email,180).toLowerCase(),cleanText(phone,30),cleanText(message,800),`+${hours} hours`);
  return { id:Number(result.lastInsertRowid),token,url:`/invite.html?token=${token}`,expiresInHours:hours };
}
route('POST', /^\/api\/admin\/guide-invitations$/, async (req,res) => { const admin=requireUser(req,res,['admin']);if(!admin)return;const data=await body(req);if(!cleanText(data.name)||!/^\S+@\S+\.\S+$/.test(cleanText(data.email)))return fail(res,400,'Guide name and valid email are required');reply(res,201,{invitation:createInvitation({kind:'guide_onboarding',inviterUserId:admin.id,name:data.name,email:data.email,phone:data.phone,message:data.message,hours:168})}); });
route('GET', /^\/api\/admin\/invitations$/, (req,res,url) => { const admin=requireUser(req,res,['admin']);if(!admin)return;const kind=url.searchParams.get('kind')||'guide_onboarding';db.prepare("UPDATE invitations SET status='expired' WHERE status IN ('sent','opened') AND expires_at<=datetime('now')").run();reply(res,200,{invitations:db.prepare('SELECT i.*,(SELECT a.status FROM guide_applications a WHERE lower(a.email)=lower(i.recipient_email) ORDER BY a.created_at DESC LIMIT 1) application_status FROM invitations i WHERE i.kind=? ORDER BY i.created_at DESC LIMIT 200').all(kind)}); });
route('POST', /^\/api\/guide\/client-invitations$/, async (req,res) => { const user=requireUser(req,res,['guide']);if(!user)return;const guide=db.prepare('SELECT id FROM guide_profiles WHERE user_id=?').get(user.id);if(!guide)return fail(res,404,'Guide profile not found');const data=await body(req);if(!cleanText(data.name)||(!cleanText(data.email)&&!cleanText(data.phone)))return fail(res,400,'Client name and email or phone are required');reply(res,201,{invitation:createInvitation({kind:'client_booking',inviterUserId:user.id,guideId:guide.id,name:data.name,email:data.email,phone:data.phone,message:data.message,hours:336})}); });
route('GET', /^\/api\/guide\/invitations$/, (req,res) => { const user=requireUser(req,res,['guide']);if(!user)return;db.prepare("UPDATE invitations SET status='expired' WHERE status IN ('sent','opened') AND expires_at<=datetime('now')").run();reply(res,200,{invitations:db.prepare("SELECT * FROM invitations WHERE inviter_user_id=? AND kind='client_booking' ORDER BY created_at DESC LIMIT 200").all(user.id)}); });
route('GET', /^\/api\/invitations\/([A-Za-z0-9_-]+)$/, (req,res,_url,match) => { const tokenHash=sha256(match[1]);let invite=db.prepare("SELECT i.*,g.display_name guide_name,g.primary_location,g.profile_photo,(SELECT a.status FROM guide_applications a WHERE lower(a.email)=lower(i.recipient_email) ORDER BY a.created_at DESC LIMIT 1) application_status FROM invitations i LEFT JOIN guide_profiles g ON g.id=i.guide_id WHERE i.token_hash=?").get(tokenHash);if(!invite)return fail(res,404,'Invitation not found');if(new Date(`${invite.expires_at}Z`)<=new Date()&&['sent','opened'].includes(invite.status)){db.prepare("UPDATE invitations SET status='expired' WHERE id=?").run(invite.id);invite.status='expired';}else if(invite.status==='sent'){db.prepare("UPDATE invitations SET status='opened' WHERE id=?").run(invite.id);invite.status='opened';}reply(res,200,{invitation:{id:invite.id,kind:invite.kind,name:invite.recipient_name,email:invite.recipient_email,phone:invite.recipient_phone,message:invite.message,status:invite.status,expiresAt:invite.expires_at,applicationStatus:invite.application_status,guideId:invite.guide_id,guideName:invite.guide_name,guideLocation:invite.primary_location,guidePhoto:invite.profile_photo}}); });
route('POST', /^\/api\/invitations\/([A-Za-z0-9_-]+)\/accept$/, (req,res,_url,match) => { const user=requireUser(req,res,['traveler']);if(!user)return;const invite=db.prepare("SELECT * FROM invitations WHERE token_hash=? AND kind='client_booking' AND status IN ('sent','opened') AND expires_at>datetime('now')").get(sha256(match[1]));if(!invite)return fail(res,410,'Invitation is invalid or expired');db.prepare("UPDATE invitations SET status='accepted',accepted_user_id=?,accepted_at=datetime('now') WHERE id=?").run(user.id,invite.id);reply(res,200,{guideId:invite.guide_id,status:'accepted'}); });
route('POST', /^\/api\/guide-onboarding\/([A-Za-z0-9_-]+)\/activate$/, async (req,res,_url,match) => { const invite=db.prepare("SELECT * FROM invitations WHERE token_hash=? AND kind='guide_onboarding' AND status='accepted'").get(sha256(match[1]));if(!invite)return fail(res,410,'Onboarding invitation is not ready for activation');const application=db.prepare("SELECT * FROM guide_applications WHERE lower(email)=lower(?) AND status='approved' ORDER BY created_at DESC LIMIT 1").get(invite.recipient_email);if(!application)return fail(res,409,'Your guide application must be approved before activation');const data=await body(req),password=String(data.password||'');if(password.length<8)return fail(res,400,'Use at least 8 characters for your password');const user=db.prepare("SELECT * FROM users WHERE lower(email)=lower(?) AND role='guide'").get(invite.recipient_email);if(!user)return fail(res,404,'Approved guide account not found');db.prepare("UPDATE users SET password_hash=?,updated_at=datetime('now') WHERE id=?").run(hashPassword(password),user.id);createSession(res,user.id);reply(res,200,{user:publicUser(user),redirect:'/guide-admin.html'}); });

function requestedDates(start,end){const dates=[];for(let d=new Date(`${start}T00:00:00Z`),last=new Date(`${end}T00:00:00Z`);d<=last;d.setUTCDate(d.getUTCDate()+1))dates.push(d.toISOString().slice(0,10));return dates;}
route('POST', /^\/api\/booking-requests$/, async (req,res) => { const traveler=requireUser(req,res,['traveler']);if(!traveler)return;const data=await body(req),guideId=Number(data.guideId),start=String(data.startDate||''),end=String(data.endDate||''),party=Number(data.travelers);if(!/^\d{4}-\d{2}-\d{2}$/.test(start)||!/^\d{4}-\d{2}-\d{2}$/.test(end)||start>end||party<1||party>12)return fail(res,400,'Valid dates and traveler count are required');const guide=db.prepare("SELECT * FROM guide_profiles WHERE id=? AND verification_status='approved'").get(guideId);if(!guide)return fail(res,404,'Guide not found');const dates=requestedDates(start,end);if(dates.length>31)return fail(res,400,'Requests cannot exceed 31 days');const available=new Set(db.prepare("SELECT date FROM availability WHERE guide_id=? AND status='available' AND date BETWEEN ? AND ?").all(guideId,start,end).map(x=>x.date));if(dates.some(d=>!available.has(d)))return fail(res,409,'One or more selected dates are no longer available');let invitationId=null;if(data.invitationToken){const invite=db.prepare("SELECT * FROM invitations WHERE token_hash=? AND guide_id=? AND kind='client_booking' AND status IN ('sent','opened','accepted') AND expires_at>datetime('now')").get(sha256(String(data.invitationToken)),guideId);if(invite){invitationId=invite.id;db.prepare("UPDATE invitations SET status='accepted',accepted_user_id=?,accepted_at=coalesce(accepted_at,datetime('now')) WHERE id=?").run(traveler.id,invite.id);}}const estimate=guide.daily_rate*dates.length,result=db.prepare(`INSERT INTO booking_requests(traveler_id,guide_id,invitation_id,start_date,end_date,travelers,focus,message,estimated_amount,response_deadline) VALUES(?,?,?,?,?,?,?,?,?,datetime('now','+24 hours'))`).run(traveler.id,guideId,invitationId,start,end,party,cleanText(data.focus,100),cleanText(data.message,1000),estimate),id=Number(result.lastInsertRowid),reference=`REQ-${String(id).padStart(6,'0')}`;db.prepare('UPDATE booking_requests SET reference=? WHERE id=?').run(reference,id);reply(res,201,{request:{id,reference,guideId,startDate:start,endDate:end,travelers:party,focus:cleanText(data.focus,100),estimatedAmount:estimate,paymentArrangement:'direct_with_guide',status:'pending',responseDeadline:'24 hours'}}); });
route('GET', /^\/api\/traveler\/booking-requests$/, (req,res) => { const user=requireUser(req,res,['traveler']);if(!user)return;db.prepare("UPDATE booking_requests SET status='expired' WHERE status='pending' AND response_deadline<=datetime('now')").run();reply(res,200,{requests:db.prepare('SELECT r.*,g.display_name guide_name,g.primary_location FROM booking_requests r JOIN guide_profiles g ON g.id=r.guide_id WHERE r.traveler_id=? ORDER BY r.created_at DESC').all(user.id)}); });
route('PATCH', /^\/api\/traveler\/booking-requests\/(\d+)$/, async (req,res,_url,match) => { const user=requireUser(req,res,['traveler']);if(!user)return;const data=await body(req);if(data.action!=='withdraw')return fail(res,400,'Action must be withdraw');const result=db.prepare("UPDATE booking_requests SET status='withdrawn',responded_at=datetime('now') WHERE id=? AND traveler_id=? AND status='pending'").run(Number(match[1]),user.id);if(!result.changes)return fail(res,404,'Pending booking request not found');reply(res,200,{requestId:Number(match[1]),status:'withdrawn'}); });
route('GET', /^\/api\/guide\/booking-requests$/, (req,res) => { const user=requireUser(req,res,['guide']);if(!user)return;const guide=db.prepare('SELECT id FROM guide_profiles WHERE user_id=?').get(user.id);if(!guide)return fail(res,404,'Guide profile not found');db.prepare("UPDATE booking_requests SET status='expired' WHERE status='pending' AND response_deadline<=datetime('now')").run();reply(res,200,{requests:db.prepare('SELECT r.*,u.name traveler_name,u.phone traveler_phone,u.email traveler_email FROM booking_requests r JOIN users u ON u.id=r.traveler_id WHERE r.guide_id=? ORDER BY CASE r.status WHEN \'pending\' THEN 0 ELSE 1 END,r.created_at DESC').all(guide.id)}); });
route('PATCH', /^\/api\/guide\/booking-requests\/(\d+)$/, async (req,res,_url,match) => { const user=requireUser(req,res,['guide']);if(!user)return;const guide=db.prepare('SELECT id FROM guide_profiles WHERE user_id=?').get(user.id);const request=db.prepare("SELECT * FROM booking_requests WHERE id=? AND guide_id=? AND status='pending' AND response_deadline>datetime('now')").get(Number(match[1]),guide?.id);if(!request)return fail(res,404,'Pending booking request not found');const data=await body(req),decision=data.decision;if(!['accept','decline'].includes(decision))return fail(res,400,'Decision must be accept or decline');if(decision==='decline'){db.prepare("UPDATE booking_requests SET status='declined',guide_note=?,responded_at=datetime('now') WHERE id=?").run(cleanText(data.note,500),request.id);return reply(res,200,{requestId:request.id,status:'declined'});}const dates=requestedDates(request.start_date,request.end_date),available=new Set(db.prepare("SELECT date FROM availability WHERE guide_id=? AND status='available' AND date BETWEEN ? AND ?").all(guide.id,request.start_date,request.end_date).map(x=>x.date));if(dates.some(d=>!available.has(d)))return fail(res,409,'Dates are no longer fully available');db.exec('BEGIN');try{const daily=db.prepare('SELECT daily_rate FROM guide_profiles WHERE id=?').get(guide.id).daily_rate,subtotal=daily*dates.length,bookingResult=db.prepare(`INSERT INTO bookings(traveler_id,guide_id,start_date,end_date,travelers,focus,message,daily_rate,subtotal,service_fee,total,status) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)`).run(request.traveler_id,guide.id,request.start_date,request.end_date,request.travelers,request.focus,request.message,daily,subtotal,0,subtotal,'confirmed'),bookingId=Number(bookingResult.lastInsertRowid),reference=`FMG-${String(bookingId).padStart(6,'0')}`;db.prepare('UPDATE bookings SET reference=? WHERE id=?').run(reference,bookingId);for(const date of dates)db.prepare("UPDATE availability SET status='booked',booking_id=? WHERE guide_id=? AND date=? AND status='available'").run(bookingId,guide.id,date);db.prepare("UPDATE booking_requests SET status='accepted',guide_note=?,booking_id=?,responded_at=datetime('now') WHERE id=?").run(cleanText(data.note,500),bookingId,request.id);db.prepare("INSERT INTO direct_payment_records(booking_id,status,note) VALUES(?,?,?)").run(bookingId,'not_recorded','Payment arranged directly between traveler and guide.');db.exec('COMMIT');reply(res,200,{requestId:request.id,status:'accepted',booking:{id:bookingId,reference,status:'confirmed',paymentArrangement:'direct_with_guide'}});}catch(error){db.exec('ROLLBACK');throw error;} });
route('PATCH', /^\/api\/guide\/bookings\/(\d+)\/payment-record$/, async (req,res,_url,match) => { const user=requireUser(req,res,['guide']);if(!user)return;const guide=db.prepare('SELECT id FROM guide_profiles WHERE user_id=?').get(user.id),booking=db.prepare('SELECT id FROM bookings WHERE id=? AND guide_id=?').get(Number(match[1]),guide?.id);if(!booking)return fail(res,404,'Booking not found');const data=await body(req);if(!['not_recorded','deposit_paid','paid_in_full','pay_on_arrival'].includes(data.status))return fail(res,400,'Invalid payment record status');db.prepare(`INSERT INTO direct_payment_records(booking_id,status,amount_recorded,note,recorded_by,recorded_at) VALUES(?,?,?,?,?,datetime('now')) ON CONFLICT(booking_id) DO UPDATE SET status=excluded.status,amount_recorded=excluded.amount_recorded,note=excluded.note,recorded_by=excluded.recorded_by,recorded_at=excluded.recorded_at`).run(booking.id,data.status,Number(data.amount||0),cleanText(data.note,500),user.id);reply(res,200,{ok:true}); });
route('POST', /^\/api\/bookings$/, (req,res) => { if(!requireUser(req,res,['traveler']))return; fail(res,410,'Instant booking is disabled. Send a booking request for the guide to confirm.'); });
route('GET', /^\/api\/traveler\/bookings$/, (req,res) => { const user=requireUser(req,res,['traveler']);if(!user)return;const rows=db.prepare('SELECT b.*,g.display_name guide_name,d.status payment_record_status,d.amount_recorded,d.note payment_note FROM bookings b JOIN guide_profiles g ON g.id=b.guide_id LEFT JOIN direct_payment_records d ON d.booking_id=b.id WHERE b.traveler_id=? ORDER BY b.start_date DESC').all(user.id).map(bookingDto);reply(res,200,{bookings:rows}); });
route('GET', /^\/api\/guide\/bookings$/, (req,res) => { const user=requireUser(req,res,['guide']);if(!user)return;const guide=db.prepare('SELECT id FROM guide_profiles WHERE user_id=?').get(user.id);const rows=guide?db.prepare('SELECT b.*,u.name traveler_name,u.email traveler_email,u.phone traveler_phone,d.status payment_record_status,d.amount_recorded,d.note payment_note FROM bookings b JOIN users u ON u.id=b.traveler_id LEFT JOIN direct_payment_records d ON d.booking_id=b.id WHERE b.guide_id=? ORDER BY b.start_date').all(guide.id):[];reply(res,200,{bookings:rows}); });
route('GET', /^\/api\/guide\/availability$/, (req,res,url) => { const user=requireUser(req,res,['guide']);if(!user)return;const guide=db.prepare('SELECT id FROM guide_profiles WHERE user_id=?').get(user.id);if(!guide)return fail(res,404,'Guide profile not found');const from=url.searchParams.get('from')||'2026-10-01',to=url.searchParams.get('to')||'2026-10-31';reply(res,200,{guideId:guide.id,dates:db.prepare('SELECT date,status FROM availability WHERE guide_id=? AND date BETWEEN ? AND ? ORDER BY date').all(guide.id,from,to)}); });
route('PUT', /^\/api\/guide\/availability$/, async (req,res) => { const user=requireUser(req,res,['guide']);if(!user)return;const guide=db.prepare('SELECT id FROM guide_profiles WHERE user_id=?').get(user.id);if(!guide)return fail(res,404,'Guide profile not found');const data=await body(req),dates=Array.isArray(data.dates)?data.dates.slice(0,370):[];db.exec('BEGIN');try{const upsert=db.prepare(`INSERT INTO availability(guide_id,date,status) VALUES(?,?,?) ON CONFLICT(guide_id,date) DO UPDATE SET status=CASE WHEN availability.status='booked' THEN 'booked' ELSE excluded.status END`);for(const item of dates){if(/^\d{4}-\d{2}-\d{2}$/.test(item.date)&&['available','blocked'].includes(item.status))upsert.run(guide.id,item.date,item.status);}db.exec('COMMIT');reply(res,200,{updated:dates.length});}catch(e){db.exec('ROLLBACK');throw e;} });

route('POST', /^\/api\/payments\/session$/, (req,res) => { if(!requireUser(req,res,['traveler']))return; fail(res,410,'Online checkout is not enabled. Payment is arranged directly with the guide.'); });
route('POST', /^\/api\/payments\/mock-confirm$/, (req,res) => { if(!requireUser(req,res,['traveler']))return; fail(res,410,'Online checkout is not enabled. Payment is arranged directly with the guide.'); });

route('POST', /^\/api\/reviews$/, async (req,res) => { const traveler=requireUser(req,res,['traveler']);if(!traveler)return;const data=await body(req),booking=db.prepare("SELECT * FROM bookings WHERE (id=? OR reference=?) AND traveler_id=? AND status='completed'").get(Number(data.bookingId)||-1,String(data.bookingId||''),traveler.id);if(!booking)return fail(res,403,'Only completed bookings can be reviewed');const ratings=['overall','knowledge','communication','organisation','value'];if(ratings.some(k=>Number(data[k])<1||Number(data[k])>5)||cleanText(data.title,80).length<3||cleanText(data.body,1200).length<30)return fail(res,400,'Complete all ratings, title and review text');try{const result=db.prepare(`INSERT INTO reviews(booking_id,traveler_id,guide_id,overall,knowledge,communication,organisation,value,title,body,photos_json) VALUES(?,?,?,?,?,?,?,?,?,?,?)`).run(booking.id,traveler.id,booking.guide_id,...ratings.map(k=>Number(data[k])),cleanText(data.title,80),cleanText(data.body,1200),JSON.stringify(data.photos||[]));const stats=db.prepare("SELECT avg(overall) rating,count(*) count FROM reviews WHERE guide_id=? AND status='published'").get(booking.guide_id);db.prepare('UPDATE guide_profiles SET rating=?,review_count=? WHERE id=?').run(Number(stats.rating.toFixed(1)),stats.count,booking.guide_id);reply(res,201,{id:Number(result.lastInsertRowid),verified:true});}catch(e){if(String(e.message).includes('UNIQUE'))return fail(res,409,'This booking has already been reviewed');throw e;} });

export async function handleApiRequest(req,res,url) {
  try {
    const found=routes.find(r=>r.method===req.method&&r.pattern.test(url.pathname));
    if(!found)return fail(res,404,'API endpoint not found');
    const match=url.pathname.match(found.pattern);
    return await found.handler(req,res,url,match);
  } catch(error) { console.error(error); if(!res.headersSent)fail(res,error.status||500,error.status?error.message:'Internal server error');else res.end(); }
}
// FindMyGuide API route registry.
