import test, { after, before } from 'node:test';
import assert from 'node:assert/strict';
import { spawn } from 'node:child_process';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { rm } from 'node:fs/promises';

const port = 3199;
const base = `http://127.0.0.1:${port}`;
const dbPath = join(tmpdir(), `findmyguide-test-${Date.now()}.sqlite`);
let server;
let travelerCookie = '';
let adminCookie = '';
let guideCookie = '';

async function waitForServer() {
  for (let i=0;i<50;i++) {
    try { const response=await fetch(`${base}/api/health`); if(response.ok)return; } catch {}
    await new Promise(resolve=>setTimeout(resolve,50));
  }
  throw new Error('Test server did not start');
}

async function request(path, { method='GET', body, cookie } = {}) {
  const response = await fetch(`${base}${path}`, { method, headers:{ ...(body?{'Content-Type':'application/json'}:{}), ...(cookie?{Cookie:cookie}:{}) }, body:body?JSON.stringify(body):undefined });
  const data = await response.json();
  return { response, data, cookie:response.headers.get('set-cookie')?.split(';')[0] };
}

before(async()=>{ server=spawn(process.execPath,['server.mjs'],{cwd:process.cwd(),env:{...process.env,PORT:String(port),FMG_DB_PATH:dbPath,NODE_ENV:'test'},stdio:['ignore','pipe','inherit']});await waitForServer(); });
after(async()=>{server.kill('SIGTERM');await rm(dbPath,{force:true});await rm(`${dbPath}-shm`,{force:true});await rm(`${dbPath}-wal`,{force:true});});

test('health and guide discovery', async()=>{const health=await request('/api/health');assert.equal(health.response.status,200);const result=await request('/api/guides?q=Kerala');assert.equal(result.response.status,200);assert.ok(result.data.guides.some(g=>g.name==='Ravi Menon'));});

test('traveler login creates an HTTP-only session', async()=>{const result=await request('/api/auth/login',{method:'POST',body:{identity:'traveler@example.com',password:'Traveler123!',role:'traveler'}});assert.equal(result.response.status,200);assert.equal(result.data.user.role,'traveler');assert.match(result.response.headers.get('set-cookie'),/HttpOnly/);travelerCookie=result.cookie;});

test('guide invitation leads to request-to-book and only acceptance blocks dates', async()=>{const login=await request('/api/auth/login',{method:'POST',body:{identity:'guide@findmyguide.in',password:'Guide123!',role:'guide'}});guideCookie=login.cookie;const invitation=await request('/api/guide/client-invitations',{method:'POST',cookie:guideCookie,body:{name:'Meera Shah',email:'traveler@example.com',message:'Please request my open dates.'}});assert.equal(invitation.response.status,201);const token=invitation.data.invitation.token;const opened=await request(`/api/invitations/${token}`);assert.equal(opened.data.invitation.status,'opened');const first=await request('/api/booking-requests',{method:'POST',cookie:travelerCookie,body:{guideId:1,startDate:'2026-10-01',endDate:'2026-10-02',travelers:2,focus:'Birding',message:'Test request',invitationToken:token}});assert.equal(first.response.status,201);assert.equal(first.data.request.status,'pending');assert.equal(first.data.request.estimatedAmount,11000);const second=await request('/api/booking-requests',{method:'POST',cookie:travelerCookie,body:{guideId:1,startDate:'2026-10-01',endDate:'2026-10-02',travelers:1,focus:'Birding'}});assert.equal(second.response.status,201);const before=await request('/api/guides/1/availability?from=2026-10-01&to=2026-10-02');assert.equal(before.data.dates.length,2);const accepted=await request(`/api/guide/booking-requests/${first.data.request.id}`,{method:'PATCH',cookie:guideCookie,body:{decision:'accept',note:'Confirmed; pay me directly.'}});assert.equal(accepted.response.status,200);assert.equal(accepted.data.booking.status,'confirmed');const afterAccept=await request('/api/guides/1/availability?from=2026-10-01&to=2026-10-02');assert.equal(afterAccept.data.dates.length,0);const conflictingAccept=await request(`/api/guide/booking-requests/${second.data.request.id}`,{method:'PATCH',cookie:guideCookie,body:{decision:'accept'}});assert.equal(conflictingAccept.response.status,409);const withdrawn=await request(`/api/traveler/booking-requests/${second.data.request.id}`,{method:'PATCH',cookie:travelerCookie,body:{action:'withdraw'}});assert.equal(withdrawn.response.status,200);assert.equal(withdrawn.data.status,'withdrawn');const paymentRecord=await request(`/api/guide/bookings/${accepted.data.booking.id}/payment-record`,{method:'PATCH',cookie:guideCookie,body:{status:'deposit_paid',amount:3000,note:'Cash deposit'}});assert.equal(paymentRecord.response.status,200);const legacyBooking=await request('/api/bookings',{method:'POST',cookie:travelerCookie,body:{}});assert.equal(legacyBooking.response.status,410);const checkout=await request('/api/payments/session',{method:'POST',cookie:travelerCookie,body:{bookingId:accepted.data.booking.id}});assert.equal(checkout.response.status,410);});

test('only completed booking owner can publish one review', async()=>{const review=await request('/api/reviews',{method:'POST',cookie:travelerCookie,body:{bookingId:'FMG-1028',overall:5,knowledge:5,communication:5,organisation:5,value:4,title:'Outstanding field guide',body:'A thoughtful, deeply knowledgeable and beautifully paced birding experience.'}});assert.equal(review.response.status,201);assert.equal(review.data.verified,true);const duplicate=await request('/api/reviews',{method:'POST',cookie:travelerCookie,body:{bookingId:'FMG-1028',overall:5,knowledge:5,communication:5,organisation:5,value:5,title:'Again',body:'This duplicate review should be rejected by the booking constraint.'}});assert.equal(duplicate.response.status,409);});

test('admin can search and filter every operations directory', async()=>{const login=await request('/api/auth/login',{method:'POST',body:{identity:'admin@findmyguide.in',password:'Admin123!',role:'admin'}});adminCookie=login.cookie;const guides=await request('/api/admin/guides?q=Ravi&expertise=birding&limit=10',{cookie:adminCookie});assert.equal(guides.response.status,200);assert.equal(guides.data.guides.length,1);assert.equal(guides.data.guides[0].display_name,'Ravi Menon');assert.ok(guides.data.guides[0].available_date_count>=0);const users=await request('/api/admin/users?role=traveler&booked=yes&limit=10',{cookie:adminCookie});assert.equal(users.response.status,200);assert.ok(users.data.users.some(u=>u.email==='traveler@example.com'));assert.equal(users.data.meta.page,1);const bookings=await request('/api/admin/bookings?paymentStatus=deposit_paid&limit=10',{cookie:adminCookie});assert.equal(bookings.response.status,200);assert.ok(bookings.data.bookings.some(b=>b.payment_record_status==='deposit_paid'));const requests=await request('/api/admin/booking-requests?status=withdrawn&source=direct&limit=10',{cookie:adminCookie});assert.equal(requests.response.status,200);assert.ok(requests.data.requests.some(r=>r.status==='withdrawn'));const reviews=await request('/api/admin/reviews?q=Outstanding&rating=5&status=published',{cookie:adminCookie});assert.equal(reviews.response.status,200);assert.equal(reviews.data.reviews.length,1);assert.equal(reviews.data.reviews[0].booking_reference,'FMG-1028');const forbidden=await request('/api/admin/users',{cookie:travelerCookie});assert.equal(forbidden.response.status,403);const queue=await request('/api/admin/applications?status=pending',{cookie:adminCookie});assert.equal(queue.response.status,200);assert.ok(queue.data.applications.length>0);const id=queue.data.applications[0].id;const decision=await request(`/api/admin/applications/${id}`,{method:'PATCH',cookie:adminCookie,body:{decision:'approved',note:'Verified in automated test'}});assert.equal(decision.response.status,200);assert.equal(decision.data.status,'approved');});

test('admin invitation supports application, approval and guide activation', async()=>{const invited=await request('/api/admin/guide-invitations',{method:'POST',cookie:adminCookie,body:{name:'Asha Test Guide',email:'asha.test@example.com',phone:'+91 90000 00000',message:'Join our verified guide network.'}});assert.equal(invited.response.status,201);const token=invited.data.invitation.token;const application=await request('/api/guide-applications',{method:'POST',body:{name:'Asha Test Guide',email:'asha.test@example.com',phone:'+91 90000 00000',primaryLocation:'Mysuru, Karnataka',workLocations:['Nagarhole'],expertise:['Birding','Wildlife tracking'],languages:['English'],yearsExperience:6,dailyRate:5000,bio:'Experienced field guide focused on responsible wildlife encounters.',invitationToken:token}});assert.equal(application.response.status,201);const decision=await request(`/api/admin/applications/${application.data.id}`,{method:'PATCH',cookie:adminCookie,body:{decision:'approved',note:'Documents verified'}});assert.equal(decision.response.status,200);const status=await request(`/api/invitations/${token}`);assert.equal(status.data.invitation.applicationStatus,'approved');const activation=await request(`/api/guide-onboarding/${token}/activate`,{method:'POST',body:{password:'AshaGuide123!'}});assert.equal(activation.response.status,200);assert.equal(activation.data.user.role,'guide');assert.match(activation.response.headers.get('set-cookie'),/HttpOnly/);});
